name:                 json-canvas-cli
version:              0.1.0.0
visibility:           public
id:                   json-canvas-cli-0.1.0.0-inplace
key:                  json-canvas-cli-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:
    Desktop.CanvasEDSL Desktop.MdExtract Desktop.TreeCanvas
    MnemonicManifold.Brackets MnemonicManifold.Canon
    MnemonicManifold.Emit MnemonicManifold.Ids
    MnemonicManifold.JsonText MnemonicManifold.SHA256
    MnemonicManifold.Spec

import-dirs:
    /home/main/devops/knownoknowledge/packages/json-canvas/dist-newstyle/build/x86_64-linux/ghc-9.4.7/json-canvas-cli-0.1.0.0/build

library-dirs:
    /home/main/devops/knownoknowledge/packages/json-canvas/dist-newstyle/build/x86_64-linux/ghc-9.4.7/json-canvas-cli-0.1.0.0/build

library-dirs-static:
    /home/main/devops/knownoknowledge/packages/json-canvas/dist-newstyle/build/x86_64-linux/ghc-9.4.7/json-canvas-cli-0.1.0.0/build

dynamic-library-dirs:
    /home/main/devops/knownoknowledge/packages/json-canvas/dist-newstyle/build/x86_64-linux/ghc-9.4.7/json-canvas-cli-0.1.0.0/build

data-dir:             /home/main/devops/knownoknowledge/packages/json-canvas/.
hs-libraries:         HSjson-canvas-cli-0.1.0.0-inplace
depends:
    aeson-2.2.3.0-0f2cf462c0d6d62c5dbd64c38d1ae5b770bd5703061ee7dd156b462b470d260c
    base-4.17.2.0 bytestring-0.11.5.2 containers-0.6.7
    directory-1.3.7.1 filepath-1.4.2.2 text-2.0.2 time-1.12.2
    vector-0.13.2.0-78163b51c3df56cd210e75938af0d4409b7f2d49f6c8c773cfe39fda43a5e7ef

haddock-interfaces:
    /home/main/devops/knownoknowledge/packages/json-canvas/dist-newstyle/build/x86_64-linux/ghc-9.4.7/json-canvas-cli-0.1.0.0/doc/html/json-canvas-cli/json-canvas-cli.haddock

haddock-html:
    /home/main/devops/knownoknowledge/packages/json-canvas/dist-newstyle/build/x86_64-linux/ghc-9.4.7/json-canvas-cli-0.1.0.0/doc/html/json-canvas-cli
